"""Default constants for TaskSpec CRD fields."""

DEFAULT_TIMEOUT = "300s"
DEFAULT_TOTAL_TIMEOUT = "1800s"
DEFAULT_MAX_RETRIES = 2
DEFAULT_ON_MAX_RETRIES = "escalate"
DEFAULT_OUTPUT_FORMAT = "pr"
DEFAULT_PR_TITLE_PREFIX = "nubi:"
DEFAULT_PR_DRAFT = True
DEFAULT_DECOMPOSITION_ALLOW = False
DEFAULT_DECOMPOSITION_MAX_DEPTH = 2
DEFAULT_DECOMPOSITION_MAX_SUBTASKS = 5
DEFAULT_REVIEW_ENABLED = True
DEFAULT_MONITORING_SUMMARY = True
DEFAULT_RESOURCE_CPU = "1"
DEFAULT_RESOURCE_MEMORY = "512Mi"
DEFAULT_BRANCH = "main"
